### ISSUE TITLE
Add message hover background color

### ISSUE THREAD

**Issue by mikestecker** [dennisfrank/decent-discord#1]
Feel free to add message hover colors similar to Slack:

```css
:root {
  --theme-light-message-hover-bg-color: rgba(0,0,0,.03);
  --theme-dark-message-hover-bg-color: rgba(255,255,255,.03);
}

.theme-light [class*="containerCozyBounded-"]:hover {
    background-color: var(--theme-light-message-hover-bg-color);
}
.theme-dark [class*="containerCozyBounded-"]:hover {
    background-color: var(--theme-dark-message-hover-bg-color);
}
```
