### ISSUE TITLE
Update server indicators

### ISSUE THREAD

**Issue by dennisfrank** [dennisfrank/decent-discord#14]
I sometimes don’t recognize the vertical white bar as the active server indicator. Perhaps we can make the current server and servers with unread posts more easily distinguishable from each other.

<img width="143" alt="image" src="https://user-images.githubusercontent.com/65968/53288543-b1876b00-3789-11e9-8d47-075790c546be.png">

**Comment by dennisfrank** [comment]
Perhaps we can also customize the appearance of non-active server icons like this:

<img width="152" alt="image" src="https://user-images.githubusercontent.com/65968/53499902-9c704c00-3aa9-11e9-9140-b4f54b088860.png">

```css
[class*="guildInner-"]:not(:hover) {
  filter: grayscale(100%);
}

[class*="selected-"] [class*="guildInner-"]:not(:hover) {
  filter: none;
}
```
