### ISSUE TITLE
Consider updating the message action button styling

### ISSUE THREAD

**Issue by jalendport** [dennisfrank/decent-discord#16]
I have the hardest time trying to find these things when I hover over messages:
![screen shot 2019-02-23 at 14 39 16](https://user-images.githubusercontent.com/6537823/53290912-e808ba00-3778-11e9-80d1-9fdb8bb933a5.png)

Would be nice if we could at least increase the contrast (maybe bump the size a tad as well. If we could come up with more of a floating toolbar style like Slack, I think it would be even better:
![image](https://user-images.githubusercontent.com/6537823/53290921-0ff81d80-3779-11e9-88a8-c8ab03056286.png)

**Comment by dennisfrank** [comment]
A first step:

```css
[class*="messageCozy-"]:hover [class*="buttonContainer-"] > * {
    visibility: visible;
    opacity: 1;
}
```
