### ISSUE TITLE
Hide server bar by default and show on hover

### ISSUE THREAD

**Issue by dennisfrank** [dennisfrank/decent-discord#18]
![hidden channel bar](https://user-images.githubusercontent.com/65968/53811328-6f181800-3f59-11e9-86dc-e0e74dda32eb.gif)

```css
/* Server bar transition */
[class*="guildsWrapper-"] {
    transition: .2s width ease-out;
}

/* Hide server bar */
[class*="guildsWrapper-"]:not(:hover) {
    position: relative;
    width: 0;
    overflow: visible;
    contain: unset;
}

/* Hide server bar content */
[class*="guildsWrapper-"]:not(:hover) * {
    display: none;
}

/* Invisible hover area */
[class*="guildsWrapper-"]::after {
    content: "" !important;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 80%;
    width: 20px;
    z-index: 99999;
}


/* Min width for messages */
[class*="containerCozyBounded-"] {
    min-width: 200px;
    overflow-x: scroll;
}
```
